language: java
#jkd:
#- oraclejdk8
#jdk: oraclejdk8
notifications:
  email: false
script:
- sudo apt-get install build-essential g++ libexpat1-dev libfontconfig1-dev libfreetype6-dev libicu-dev libjpeg62-turbo-dev libpng12-dev libssl-dev zlib1g-dev
#- sudo apt-get udpdate
#- sudo apt-get install libicu52
- mvn appengine:update
#deploy:
#  provider: gae
#  project: avaliacaoastrea